- name: configure mysql server
  hosts: mysql
  become: true
  tasks:
    - name: install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: present
    - name: start the mysql server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true
    # - name: set mysql password
    #   command: mysql_secure_installation --set-root-pass RoboShop@1
    #   register: result
    #   failed_when: "result.rc != 0 and 'already secured' not in result.stderr"
    #   changed_when: result.rc == 0
    # - name: pring result
    #   ansible.builtin.debug:
    #     var: result
    # to work with ansible.mysql run below command along with pymysql
    # ansible-galaxy collection install ansible.mysql
    - name: Install community.mysql collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.mysql
      delegate_to: localhost
      run_once: true
      register: result
      changed_when: "'was installed' in result.stdout"
    - name: print result
      debug:
        var: result
    - name: Install PyMySQL (required by community.mysql)
      ansible.builtin.pip:
        name: PyMySQL
        state: present
    - name: Set MySQL root password (initial setup)
      ansible.mysql.mysql_user:
        name: root
        password: "RoboShop@1"
        login_user: root
        login_password: "RoboShop@1"
        host_all: true
        state: present
      #no_log: true

